[unstable]
# core ライブラリはコンパイル済みで提供されているが、別ターゲット向けに使う場合は再コンパイルする必要あり
# compiler_builtins がcore が依存してるので合わせて必要。
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"